// Alias sync exports for plain-path frontend calls, so the generator picks them up.
export {
  AcceptFriendRequestPlainError,
  AcceptFriendRequestPlainRequest,
  AcceptFriendRequestPlainResponse,
  DeletePostResponse,
  DeletePostResponseError,
  DenyFriendRequestPlainError,
  DenyFriendRequestPlainRequest,
  DenyFriendRequestPlainResponse,
  EditPostPlainError,
  EditPostPlainRequest,
  EditPostPlainResponse,
  GetAllUsersPlain,
  GetFeedForUserBySessionPlain,
  GetFeedForUserBySessionTokenPlain,
  GetFeedForUserPlain,
  GetFriendsPlain,
  GetMyPostsPlain,
  GetPostsByAuthorByAuthorPlain,
  GetPostsByAuthorByAuthorUsernamePlain,
  GetPostsByAuthorPlain,
  GetReceivedFriendRequestsPlain,
  GetSentFriendRequestsPlain,
  GetUserByUsernamePlain,
  RemoveFriendPlainError,
  RemoveFriendPlainRequest,
  RemoveFriendPlainResponse,
  SendFriendRequestPlainError,
  SendFriendRequestPlainRequest,
  SendFriendRequestPlainResponse,
} from "./hatch.syncs.ts";

// Commenting query/respond aliases (plain path variants)
export {
  AddCommentPlainError,
  AddCommentPlainRequest,
  AddCommentPlainResponse,
  AddEntryPlainError,
  AddEntryPlainRequest,
  AddEntryPlainResponse,
  ConfirmUploadPlainError,
  ConfirmUploadPlainRequest,
  ConfirmUploadPlainResponse,
  CreatePostPlainError,
  CreatePostPlainRequest,
  CreatePostPlainResponse,
  DeleteCommentPlainError,
  DeleteCommentPlainRequest,
  DeleteCommentPlainResponse,
  DeletePostPlainRequest,
  EditCommentPlainError,
  EditCommentPlainRequest,
  EditCommentPlainResponse,
  EndSessionPlainError,
  EndSessionPlainRequest,
  EndSessionPlainResponse,
  GetCommentByCommentIdPlain,
  GetCommentPlain,
  GetCommentsByAuthorByUsernamePlain,
  GetCommentsByAuthorPlain,
  GetCommentsForPostByPostIDPlain,
  GetCommentsForPostByPostIdPlain,
  GetCommentsForPostPlain,
  GetEntriesInSessionPlain,
  RequestUploadUrlPlain,
  RequestUploadUrlPlainError,
  RequestUploadUrlPlainResponse,
  StartSessionPlainError,
  StartSessionPlainRequest,
  StartSessionPlainResponse,
} from "./hatch.syncs.ts";
